#!/bin/sh
PROJECT=xd

CAPSPROJECT=`echo $PROJECT | tr '[:lower:]' '[:upper:]'`

cvsremove

cd $PROJECT

make/clean
# make/man
# make/manual

export $CAPSPROJECT=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

