#!/bin/bash

_project_=xd
_product_=xd

echo if any modified or untracked files are shown, handle these first:
echo
git st
echo -n "Continue [y/n] ? "
read yesno
[ "$yesno" == "y" ] || exit 0


echo -n "Need to (re)create ${_project_}'s wip files for gh-pages [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    git co master

    cd ${_product_}
    ./build man

    ./build github
    ./build distclean
    cd ..    
    git co gh-pages

    cp -r ../wip/changelog.txt ../wip/${_product_}man.html .
fi

echo
echo -n "Check index.yo: version and last 5 releases [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    emacs index.yo
fi

yodl2html index.yo || exit 1

echo "Running 'git st': no untracked files or ignorable files should be shown"
git st

echo

echo -n "git ci changes to index.html etc., push the result and \
git co master [y/n] ? "

read yesno

if [ "$yesno" == "y" ] ; then
    RELEASE=`head -n1 ../wip/release.yo | 
                sed 's/SUBST(_CurVers_)(\(.*\))/\1/'`

    msgDefault="gh-pages for release ${RELEASE}"

    echo -n "Enter the ci message [default: $msgDefault]"

    read msg;

    [ "$msg" == "" ] && msg=$msgDefault

    git ci -am "$msg"
    git push
    git co master
fi








