#!/bin/sh

. INSTALL.cf
. make/parameters
. make/substitutions
. make/scripts

req rm -rf debian/${PROJECT} debian/${PROJECT}.substvars build-stamp configure-stamp

eval "test \"\$$MINIMAL\" == \"minimal\""

if [ $? == 0 ]
then
    echo "
    PERFORMED MINIMAL CLEANUP
    "
    exit 0
fi

req rm -rf $LIBRARY tmp o */o 
req rm -rf manual/Yodl/manual-*-stamp release.{yo,h} 
