#!/bin/sh

. INSTALL.cf
# . make/parameters
# . make/substutions
. make/scripts

make/special

mkdir -p tmp/man tmp/manhtml

MANPAGE=../tmp/man/${PROJECT}.1
MANHTML=../tmp/manhtml/${PROJECT}man.html

req cd manpage

if [ ! -e $MANPAGE -o ${PROJECT}.yo -nt $MANPAGE -o \
    ../release.yo -nt $MANPAGE ] 
then
    req yodl2html -o $MANHTML ${PROJECT}
    req yodl2man -o $MANPAGE ${PROJECT}
fi
