#!/bin/sh

. INSTALL.cf
# . make/parameters
# . make/substutions
. make/scripts

make/special

mkdir -p tmp/manual/{LaTeX,html,pdf,ps,text}

req cd manual/Yodl

for yo in *.yo */*.yo
do
    if [ ! -e manual-yo-stamp -o $yo -nt manual-yo-stamp ]
    then
        req yodl2html ${PROJECT}.yo
        req touch manual-yo-stamp
        req mv *.html ../../tmp/manual/html
    fi
done

if [ ! -e manual-latex-stamp ]
then
    req yodl2latex -o ../../tmp/manual/LaTeX/${PROJECT}.latex ${PROJECT}.yo
    (
        req cd ../../tmp/manual/LaTeX
        latex ${PROJECT}.latex
        latex ${PROJECT}.latex
        req latex ${PROJECT}.latex
    )
    req touch manual-latex-stamp
fi

(
    req cd ../../tmp/manual/LaTeX
    [ ! -e ../ps/${PROJECT}.ps -o ${PROJECT}.dvi -nt ../ps/${PROJECT}.ps ] &&
        req dvips -o ../ps/${PROJECT}.ps ${PROJECT}.dvi
)

(
    req cd ../../tmp/manual/ps
    [ ! -e ../pdf/${PROJECT}.pdf -o ${PROJECT}.ps -nt ../pdf/${PROJECT}.pdf ] &&
        req ps2pdf ${PROJECT}.ps ../pdf/${PROJECT}.pdf
)

STEALTHTXT=../../tmp/manual/text/${PROJECT}.txt
for yo in *.yo */*.yo
do
    if [ ! -e $STEALTHTXT -o $yo -nt $STEALTHTXT ]
    then
        req yodl2txt -o $STEALTHTXT ${PROJECT}.yo
    fi
done

