/*                              xd.h

   A C++ header file generated by cpp for xd.cc

*/

#ifndef _xd_H_
#define _xd_H_


//  THERE'S NOTHING BEYOND HERE FOR YOU TO EDIT

#include "configure.h"

// Version and year are used in usage.cc only

// Enter C++ includes, etc. below the next line...
#include <stdio.h>
#include <stdlib.h>

#include "args/args.h"
#include "icerror/icerror.h"

#include "Command/Command.h"
#include "Match/Match.h"
#include "Config/Config.h"
#include "Arbiter/Arbiter.h" 

void usage(Args const &args);                   // give usage info

#endif
